<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);IDE0063;IDE0130;</NoWarn>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <Content Include="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <None Remove="appsettings.*.json" />
    <Content Include="appsettings.*.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Volo.Abp.Autofac" />
  </ItemGroup>

  <ItemGroup Label="Yuu">
    <PackageReference Include="Yuu.AspNetCore.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yuu.Eip.Application.Contracts\Yuu.Eip.Application.Contracts.csproj" />
    <ProjectReference Include="..\Yuu.Eip.EntityFrameworkCore\Yuu.Eip.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.local-dev.json" />
  </ItemGroup>

</Project>
