<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Yuu.Eip.Domain\Yuu.Eip.Domain.csproj" />
    <ProjectReference Include="..\Yuu.Eip.TestBase\Yuu.Eip.TestBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

</Project>
