<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Yuu.Eip.EntityFrameworkCore\Yuu.Eip.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Yuu.Eip.Application.Tests\Yuu.Eip.Application.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

</Project>
