<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Yuu.Eip.Application\Yuu.Eip.Application.csproj" />
    <ProjectReference Include="..\Yuu.Eip.Domain.Tests\Yuu.Eip.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

</Project>
