<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\Yuu.Eip.Application.Contracts\Yuu.Eip.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client.IdentityModel" />
    <PackageReference Include="Volo.Abp.Account.HttpApi.Client" />
    <PackageReference Include="Volo.Abp.Identity.HttpApi.Client" />
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi.Client" />
    <PackageReference Include="Volo.Abp.TenantManagement.HttpApi.Client" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi.Client" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi.Client" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*generate-proxy.json" />
    <Content Remove="**\*generate-proxy.json" />
  </ItemGroup>

</Project>
