<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yuu.Eip.Application.Contracts\Yuu.Eip.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Volo.Abp.Account.HttpApi" />
    <PackageReference Include="Volo.Abp.Identity.HttpApi" />
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" />
    <PackageReference Include="Volo.Abp.TenantManagement.HttpApi" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" />
  </ItemGroup>

</Project>
